name: Angular CI Pipeline

on:
  push:
    branches:
      - main
      - Feature
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Angular App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ProjectA
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm install
      - name: Build Angular App
        run: npm run build --if-present

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: build # Ensures tests run only after build succeeds
    defaults:
      run:
        working-directory: ProjectA
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm install
      - name: Run Unit Tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless

  notify:
    name: Send Email Notification
    runs-on: ubuntu-latest
    needs: [build, test] # Ensure this job runs after both build and test jobs
    if: always() # Always run this job regardless of success or failure
    steps:
      - name: Send Success Email
        if: needs.build.result == 'success' && needs.test.result == 'success'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          from: ${{ secrets.EMAIL_USERNAME }}
          to: ramathabathemokete@gmail.com
          subject: "Angular Component - Success"
          body: |
            Hi Team,
            I’m thrilled to let you know that our Angular Component has passed successfully! 🚀 The Build and Test jobs completed without any issues.
            Your commitment to quality and excellence is truly inspiring. With each successful pipeline, we move closer to delivering exceptional value to our users.

  create-pr:
    name: Create PR from Feature to Main
    runs-on: ubuntu-latest
    needs: [build, test] # Ensure this job runs only after both build and test jobs succeed
    if: github.ref == 'refs/heads/Feature' && github.event_name == 'push' && needs.build.result == 'success' && needs.test.result == 'success'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.TOKEN_HUB }}
          base: main # The target branch
          head: Feature # The source branch
          title: "Merge Feature into Main"
          body: "This is an automated PR to merge changes from Feature into Main."
